name: Test Tagging

on:
  push:
    branches: 
      - testworkflow

jobs:
  build:
    name: Test tagging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Version
        run: echo ::set-env name=REL_VERSION::$(cat ./version)

      - name: Create changlog.md
        uses: ssgglobal/yaml-release-action@v0.1.0
        with:
          version: ${{ env.REL_VERSION }}
          release: './release.yml'
          markdown: './changelog.md'

      - name: Set changlog.md data in env var
        run: |
          echo ::set-env name=REL_NAME::$(head -n 1 ./changelog.md | tr -d '#')

      - name: Tag release
        uses: jbolda/create-release@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'v${{ env.REL_VERSION }}'
          release_name: ${{ env.REL_NAME }}
          body_path: ./changelog.md
